# Generated by Django 5.2.1 on 2026-04-14 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permanentscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='permanent_slot_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='permanentscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='permanent_slot_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='temporaryscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='temporary_slot_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='temporaryscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='temporary_slot_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='visit_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='weeklyscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='weekly_slot_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='weeklyscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='weekly_slot_start_before_end'),
        ),
    ]
