# Generated by Django 5.1.7 on 2025-03-21 16:29

import delivery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageID', models.CharField(default=delivery.models.generate_package_id, editable=False, max_length=12, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate for geolocation', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate for geolocation', max_digits=9)),
                ('recipient', models.CharField(max_length=50)),
                ('recipientPhoneNumber', models.CharField(max_length=15)),
                ('deliveryDate', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Package weight (e.g., in kilograms)', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=15, unique=True)),
                ('kilogramCapacity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isUsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeID', models.CharField(default=delivery.models.generate_package_id, editable=False, max_length=12, unique=True)),
                ('packageSequence', models.JSONField(default=list, help_text='Ordered list of Package IDs representing delivery sequence')),
                ('mapRoute', models.JSONField(default=list, help_text='A map drawing of the route')),
                ('isActive', models.BooleanField(default=True)),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='delivery.truck')),
            ],
        ),
    ]
