# Generated by Django 5.2.3 on 2025-06-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_package_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(help_text='Date when the delivery was completed')),
                ('total_packages', models.IntegerField(default=0, help_text='Total number of packages delivered')),
                ('total_kilos', models.DecimalField(decimal_places=2, default=0.0, help_text='Total weight of packages delivered in kilograms', max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Duration of the delivery journey in hours', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_packages', models.ManyToManyField(help_text='Packages that were delivered in this journey', related_name='delivery_history', to='delivery.package')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to=settings.AUTH_USER_MODEL)),
                ('route_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='delivery.routeassignment')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='delivery.truck')),
            ],
            options={
                'ordering': ['-delivery_date'],
                'unique_together': {('delivery_date', 'driver')},
            },
        ),
    ]
