# Generated by Django 5.2.3 on 2025-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='undelivered_kilos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Total weight of packages that couldn't be delivered in kilograms", max_digits=8),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='undelivered_packages',
            field=models.IntegerField(default=0, help_text="Total number of packages that couldn't be delivered"),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='undelivered_packages_list',
            field=models.ManyToManyField(help_text="Packages that couldn't be delivered in this journey", related_name='undelivered_history', to='delivery.package'),
        ),
    ]
