# Generated by Django 5.2.4 on 2025-07-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryhistory_undelivered_kilos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
