# Generated by Django 5.2.4 on 2025-07-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_and_user_company_verified'),
        ('delivery', '0005_package_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='authentication.company')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Office where the package is currently stored (if undelivered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='delivery.office'),
        ),
    ]
