# Generated by Django 4.1.7 on 2025-08-06 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_office_package_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_deliveries', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.office')),
                ('packages', models.ManyToManyField(help_text='Packages that were delivered to this office', related_name='office_deliveries', to='delivery.package')),
                ('route_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_deliveries', to='delivery.routeassignment')),
            ],
            options={
                'ordering': ['-delivery_date'],
                'unique_together': {('driver', 'office', 'delivery_date')},
            },
        ),
    ]
