# Generated by Django 5.2.5 on 2025-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_officedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivered_to_office',
            field=models.BooleanField(default=False, help_text='Whether the package was delivered to an office instead of the recipient'),
        ),
    ]
