# Generated by Django 5.2.1 on 2025-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_package_delivered_to_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipientEmail',
            field=models.EmailField(blank=True, help_text='Email address of the package recipient for notifications', max_length=254, null=True),
        ),
    ]
