# Generated by Django 5.2.5 on 2025-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_package_recipientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientEmail',
            field=models.EmailField(blank=True, default='dimitrovradoslav12@gmail.com', help_text='Email address of the package recipient for notifications', max_length=254, null=True),
        ),
    ]
